/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundSetting: typeof import('./components/EditorRightPanel/components/StylePanel/components/BackgroundSetting/BackgroundSetting.vue')['default']
    BorderRadiusSetting: typeof import('./components/EditorRightPanel/components/StylePanel/components/BorderRadiusSetting/BorderRadiusSetting.vue')['default']
    BorderSetting: typeof import('./components/EditorRightPanel/components/StylePanel/components/BorderSetting/BorderSetting.vue')['default']
    ContextMenu: typeof import('./components/EditorLeftPanel/components/OutlinePane/components/ContextMenu/index.vue')['default']
    EditorLeftPanel: typeof import('./components/EditorLeftPanel/EditorLeftPanel.vue')['default']
    EditorMain: typeof import('./components/EditorMain/EditorMain.vue')['default']
    EditorRightPanel: typeof import('./components/EditorRightPanel/EditorRightPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FlexSettingControl: typeof import('./components/EditorRightPanel/components/LayoutPanel/components/FlexSettingControl/FlexSettingControl.vue')['default']
    FlexSettingForm: typeof import('./components/EditorRightPanel/components/FlexSettingControl/FlexSettingForm.vue')['default']
    LayoutForm: typeof import('./components/EditorRightPanel/components/LayoutPanel/components/LayoutForm/LayoutForm.vue')['default']
    LayoutPanel: typeof import('./components/EditorRightPanel/components/LayoutPanel/LayoutPanel.vue')['default']
    LeftTabs: typeof import('./components/EditorLeftPanel/components/LeftTabs/LeftTabs.vue')['default']
    MarginSetting: typeof import('./components/EditorRightPanel/components/StylePanel/components/MarginSetting/MarginSetting.vue')['default']
    OutlinePane: typeof import('./components/EditorLeftPanel/components/OutlinePane/OutlinePane.vue')['default']
    RenderersPane: typeof import('./components/EditorLeftPanel/components/RenderersPane/RenderersPane.vue')['default']
    RightTabs: typeof import('./components/EditorRightPanel/components/RightTabs/RightTabs.vue')['default']
    RIghtTabs: typeof import('./components/EditorRightPanel/components/RightTabs/RIghtTabs.vue')['default']
    StylePanel: typeof import('./components/EditorRightPanel/components/StylePanel/StylePanel.vue')['default']
    TabsLink: typeof import('./components/EditorRightPanel/components/TabsLink/TabsLink.vue')['default']
    TreeMenu: typeof import('./components/EditorLeftPanel/components/OutlinePane/components/ContextMenu/TreeMenu.vue')['default']
  }
}
